# Feature flags matching config.mk and codec_defs.mk defaults

option(ENABLE_ENCODER           "Build encoder support"                ON)
option(ENABLE_DECODER           "Build decoder support"                ON)
option(ENABLE_ENC_HEVC          "Enable HEVC encoder"                  ON)
option(ENABLE_ENC_AVC           "Enable AVC encoder"                   ON)
option(ENABLE_DEC_HEVC          "Enable HEVC decoder"                  ON)
option(ENABLE_DEC_AVC           "Enable AVC decoder"                   ON)
option(ENABLE_AVC               "Enable AVC codec"                     ON)
option(ENABLE_HEVC              "Enable HEVC codec"                    ON)
option(ENABLE_CODEC             "Enable hardware codec integration"     ON)
option(ENABLE_ENC_ITU           "Enable ITU entropy encoder"           ON)
option(ENABLE_DEC_ITU           "Enable ITU entropy decoder"           ON)
option(ENABLE_DEC_CODEC         "Enable decoder codec statistics"      ON)
option(ENABLE_ROI               "Enable Region-of-Interest support"    ON)
option(ENABLE_MICROBLAZE        "Enable Microblaze MCU firmware path"  ON)
option(ENABLE_SYNC_IP           "Enable sync-IP application"           ON)
option(ENABLE_HIGH_DYNAMIC_RANGE "Enable HDR support"                  ON)
option(ENABLE_ENC_SW_MULTIPASS  "Enable encoder software multi-pass"   ON)
option(ENABLE_LINUX_DRIVER      "Enable Linux DMA allocator driver"    ON)
option(ENABLE_64BIT             "Enable 64-bit pointer/address support" ON)
